"""
Clear Data Script for VP Investments Testing
Clears runtime/generated data while preserving configuration tables
Use this to start fresh during development and testing
"""
import asyncio
import sys
import os
from pathlib import Path
from datetime import datetime

# Add project root to path
project_root = Path.cwd()
sys.path.insert(0, str(project_root))


async def clear_data():
    """Clear all runtime data from database for fresh testing."""
    print("\n" + "=" * 80)
    print("🧹 VP INVESTMENTS - DATA CLEARING UTILITY")
    print("=" * 80 + "\n")
    
    try:
        from backend.storage.database import get_supabase_database
        
        db = await get_supabase_database()
        
        # Define what data to CLEAR (runtime/generated data)
        clear_tables = {
            # Main Signal Data
            'signals': "All trading signals generated by pipeline",
            
            # AI System
            'ai_strategies': "AI-generated trading strategies", 
            
            # Backtest Data
            'backtest_interval_tracking': "Backtest execution history",
            
            # Logs
            'runs': "Pipeline execution logs",
            
            # Scoring Data
            'signal_scoring_factors': "Signal scoring factor tracking"
        }
        
        # Define what data to PRESERVE (configuration/structural data)
        preserve_tables = {
            'guardrails_config': "Trading guardrails and risk management rules",
            'company_tickers': "Company ticker reference data (7,638 tickers)"
        }
        
        print("📋 DATA CLEARING PLAN:\n")
        print("🗑️  WILL CLEAR (Runtime/Generated Data):")
        for table, description in clear_tables.items():
            print(f"   ✅ {table:<30} - {description}")
            
        print("\n🔒 WILL PRESERVE (Configuration Data):")
        for table, description in preserve_tables.items():
            print(f"   🛡️  {table:<30} - {description}")
        
        print("\n" + "⚠️ " * 25)
        print("WARNING: This will DELETE all runtime data!")
        print("")
        print("What will be cleared:")
        print("  • All generated signals (~340 rows)")
        print("  • All AI strategies (~122 rows)")
        print("  • All backtest tracking data (~1,700 rows)")
        print("  • All pipeline run logs (~9 rows)")
        print("  • All signal scoring factors (~18 rows)")
        print("")
        print("What will be preserved:")
        print("  ✅ Configuration tables (guardrails, tickers)")
        print("  ✅ Database schema and structure")
        print("  ✅ All views")
        print("⚠️ " * 25 + "\n")
        
        # Get user confirmation
        confirmation = input("Type 'CLEAR ALL DATA' to confirm (or anything else to cancel): ").strip()
        
        if confirmation != 'CLEAR ALL DATA':
            print("\n❌ Operation cancelled. No data was cleared.\n")
            return
        
        print("\n🚀 Starting data clearing...\n")
        
        # Clear data in dependency order (child tables first, parent tables last)
        clearing_order = [
            'signal_scoring_factors',      # Independent
            'backtest_interval_tracking',  # Independent
            'ai_strategies',               # References signals (soft)
            'runs',                        # Independent
            'signals',                     # Parent table (clear last)
        ]
        
        cleared_counts = {}
        errors = []
        
        async with db.pool.acquire() as conn:
            for table in clearing_order:
                if table in clear_tables:
                    try:
                        # First count existing records
                        count_result = await conn.fetchval(f"SELECT COUNT(*) FROM {table}")
                        record_count = count_result or 0
                        
                        if record_count > 0:
                            # Delete all records
                            await conn.execute(f"DELETE FROM {table}")
                            cleared_counts[table] = record_count
                            print(f"   ✅ Cleared {record_count:>5} records from {table}")
                        else:
                            print(f"   ℹ️  {table:<30} was already empty")
                            
                    except Exception as e:
                        error_msg = f"Failed to clear {table}: {str(e)[:100]}"
                        errors.append(error_msg)
                        print(f"   ❌ {error_msg}")
                        continue
        
        # Summary
        print("\n" + "=" * 80)
        print("📊 CLEARANCE SUMMARY")
        print("=" * 80 + "\n")
        
        total_cleared = sum(cleared_counts.values())
        
        if cleared_counts:
            print("✅ Records Cleared:")
            for table, count in cleared_counts.items():
                print(f"   {table:<30} {count:>5} records")
            print(f"\n🎉 Total: {total_cleared:,} records cleared successfully!")
        else:
            print("   ℹ️  All tables were already empty")
        
        if errors:
            print("\n⚠️  Errors encountered:")
            for error in errors:
                print(f"   ❌ {error}")
        
        print("\n" + "=" * 80)
        print("✅ DATA CLEARING COMPLETED!")
        print("=" * 80)
        print("")
        print("📋 Configuration and structural data preserved:")
        print("   ✅ guardrails_config (6 rows)")
        print("   ✅ company_tickers (7,638 rows)")
        print("")
        print("🚀 System ready for fresh pipeline run:")
        print("   python -m backend.pipeline")
        print("")
        print("=" * 80 + "\n")
        
        # Close database connection
        await db.disconnect()
        
    except Exception as e:
        print(f"\n❌ CRITICAL ERROR during data clearing: {e}\n")
        import traceback
        traceback.print_exc()
        print("")


async def clear_specific_table(table_name: str):
    """Clear a specific table (for targeted testing)."""
    print(f"\n🧹 Clearing specific table: {table_name}\n")
    
    try:
        from backend.storage.database import get_supabase_database
        
        db = await get_supabase_database()
        
        async with db.pool.acquire() as conn:
            # Count records
            count = await conn.fetchval(f"SELECT COUNT(*) FROM {table_name}")
            
            if count > 0:
                # Confirm
                confirmation = input(f"Clear {count} records from {table_name}? (yes/no): ").strip().lower()
                
                if confirmation == 'yes':
                    await conn.execute(f"DELETE FROM {table_name}")
                    print(f"✅ Cleared {count} records from {table_name}\n")
                else:
                    print("❌ Cancelled\n")
            else:
                print(f"ℹ️  {table_name} is already empty\n")
        
        await db.disconnect()
        
    except Exception as e:
        print(f"❌ Error: {e}\n")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Clear VP Investments runtime data for fresh testing"
    )
    parser.add_argument(
        '--table',
        type=str,
        help='Clear specific table only (e.g., --table signals)'
    )
    
    args = parser.parse_args()
    
    if args.table:
        asyncio.run(clear_specific_table(args.table))
    else:
        asyncio.run(clear_data())
