[tool.ruff]
line-length = 120
select = ["E", "F", "I"]
exclude = [".venv", "venv", "outputs", "cache"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
pretty = true
exclude = ['outputs', 'cache']
