-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  period_type character varying NOT NULL CHECK (period_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying, 'all_time'::character varying]::text[])),
  total_signals integer NOT NULL DEFAULT 0,
  avg_overall_score numeric,
  win_rate_1d numeric,
  win_rate_3d numeric,
  win_rate_7d numeric,
  win_rate_10d numeric,
  win_rate_14d numeric,
  win_rate_30d numeric,
  win_rate_90d numeric,
  sharpe_ratio_1d numeric,
  sharpe_ratio_3d numeric,
  sharpe_ratio_7d numeric,
  sharpe_ratio_10d numeric,
  sharpe_ratio_14d numeric,
  sharpe_ratio_30d numeric,
  sharpe_ratio_90d numeric,
  max_drawdown_1d numeric,
  max_drawdown_3d numeric,
  max_drawdown_7d numeric,
  max_drawdown_10d numeric,
  max_drawdown_14d numeric,
  max_drawdown_30d numeric,
  max_drawdown_90d numeric,
  avg_return_1d numeric,
  avg_return_3d numeric,
  avg_return_7d numeric,
  avg_return_10d numeric,
  avg_return_14d numeric,
  avg_return_30d numeric,
  avg_return_90d numeric,
  avg_alpha_1d numeric,
  avg_alpha_3d numeric,
  avg_alpha_7d numeric,
  avg_alpha_10d numeric,
  avg_alpha_14d numeric,
  avg_alpha_30d numeric,
  avg_alpha_90d numeric,
  top_sector character varying,
  top_sector_avg_return numeric,
  top_sector_count integer,
  worst_sector character varying,
  worst_sector_avg_return numeric,
  worst_sector_count integer,
  sector_performance jsonb,
  avg_technical_score numeric,
  avg_fundamental_score numeric,
  avg_news_macro_score numeric,
  avg_social_alternative_score numeric,
  avg_risk_stability_score numeric,
  avg_institutional_score numeric,
  top_factors jsonb,
  signals_analyzed integer NOT NULL DEFAULT 0,
  performance_records_used integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  score_bucket_performance jsonb,
  factor_correlations jsonb,
  factor_contributions jsonb,
  group_performance jsonb,
  backtest_cumulative_returns jsonb,
  CONSTRAINT analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  signal_id uuid NOT NULL UNIQUE,
  baseline_price numeric,
  baseline_date timestamp with time zone,
  return_1d numeric,
  return_3d numeric,
  return_7d numeric,
  return_10d numeric,
  return_14d numeric,
  return_30d numeric,
  return_90d numeric,
  spy_return_1d numeric,
  spy_return_3d numeric,
  spy_return_7d numeric,
  spy_return_10d numeric,
  spy_return_14d numeric,
  spy_return_30d numeric,
  spy_return_90d numeric,
  alpha_1d numeric DEFAULT (return_1d - spy_return_1d),
  alpha_7d numeric DEFAULT (return_7d - spy_return_7d),
  alpha_30d numeric DEFAULT (return_30d - spy_return_30d),
  alpha_90d numeric DEFAULT (return_90d - spy_return_90d),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'baseline_set'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  intervals_completed jsonb,
  last_updated timestamp with time zone DEFAULT now(),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  sector text,
  sector_etf text,
  sector_return_1d real,
  sector_return_3d real,
  sector_return_7d real,
  sector_return_10d real,
  sector_return_14d real,
  sector_return_30d real,
  sector_return_90d real,
  alpha_3d real DEFAULT (return_3d - spy_return_3d),
  alpha_10d real DEFAULT (return_10d - spy_return_10d),
  alpha_14d real DEFAULT (return_14d - spy_return_14d),
  sector_alpha_1d numeric DEFAULT ((return_1d)::double precision - sector_return_1d),
  sector_alpha_3d numeric DEFAULT ((return_3d)::double precision - sector_return_3d),
  sector_alpha_7d numeric DEFAULT ((return_7d)::double precision - sector_return_7d),
  sector_alpha_10d numeric DEFAULT ((return_10d)::double precision - sector_return_10d),
  sector_alpha_14d numeric DEFAULT ((return_14d)::double precision - sector_return_14d),
  sector_alpha_30d numeric DEFAULT ((return_30d)::double precision - sector_return_30d),
  sector_alpha_90d numeric DEFAULT ((return_90d)::double precision - sector_return_90d),
  qqq_return_1d real,
  qqq_return_3d real,
  qqq_return_7d real,
  qqq_return_10d real,
  qqq_return_14d real,
  qqq_return_30d real,
  qqq_return_90d real,
  qqq_alpha_1d real DEFAULT ((return_1d)::double precision - qqq_return_1d),
  qqq_alpha_3d real DEFAULT ((return_3d)::double precision - qqq_return_3d),
  qqq_alpha_7d real DEFAULT ((return_7d)::double precision - qqq_return_7d),
  qqq_alpha_10d real DEFAULT ((return_10d)::double precision - qqq_return_10d),
  qqq_alpha_14d real DEFAULT ((return_14d)::double precision - qqq_return_14d),
  qqq_alpha_30d real DEFAULT ((return_30d)::double precision - qqq_return_30d),
  qqq_alpha_90d real DEFAULT ((return_90d)::double precision - qqq_return_90d),
  CONSTRAINT performance_pkey PRIMARY KEY (id),
  CONSTRAINT performance_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id)
);
CREATE TABLE public.signal_runs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_timestamp timestamp with time zone DEFAULT now(),
  pipeline_version character varying,
  total_tickers integer CHECK (total_tickers >= 0),
  successful_tickers integer CHECK (successful_tickers >= 0),
  failed_tickers integer CHECK (failed_tickers >= 0),
  duration_seconds numeric CHECK (duration_seconds >= 0::numeric),
  status character varying DEFAULT 'running'::character varying CHECK (status::text = ANY (ARRAY['running'::character varying, 'completed'::character varying, 'failed'::character varying, 'partial'::character varying]::text[])),
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signal_runs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.signals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  ticker character varying NOT NULL,
  overall_score numeric NOT NULL,
  technical_score numeric,
  fundamental_score numeric,
  news_macro_score numeric,
  social_alternative_score numeric,
  risk_stability_score numeric,
  institutional_smart_money_score numeric,
  rank integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  total_coverage numeric,
  technical_coverage numeric,
  fundamental_coverage numeric,
  news_macro_coverage numeric,
  social_alternative_coverage numeric,
  risk_stability_coverage numeric,
  institutional_smart_money_coverage numeric,
  company_name text,
  current_price numeric,
  sector text,
  CONSTRAINT signals_pkey PRIMARY KEY (id),
  CONSTRAINT fk_signals_run FOREIGN KEY (run_id) REFERENCES public.signal_runs(id)
);
CREATE TABLE public.signals_fundamental (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signal_id uuid NOT NULL,
  factors jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signals_fundamental_pkey PRIMARY KEY (id),
  CONSTRAINT signals_fundamental_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id)
);
CREATE TABLE public.signals_institutional_smart_money (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signal_id uuid NOT NULL,
  factors jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signals_institutional_smart_money_pkey PRIMARY KEY (id),
  CONSTRAINT signals_institutional_smart_money_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id)
);
CREATE TABLE public.signals_news_macro (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signal_id uuid NOT NULL,
  factors jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signals_news_macro_pkey PRIMARY KEY (id),
  CONSTRAINT signals_news_macro_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id)
);
CREATE TABLE public.signals_risk_stability (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signal_id uuid NOT NULL,
  factors jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signals_risk_stability_pkey PRIMARY KEY (id),
  CONSTRAINT signals_risk_stability_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id)
);
CREATE TABLE public.signals_social_alternative (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signal_id uuid NOT NULL,
  factors jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signals_social_alternative_pkey PRIMARY KEY (id),
  CONSTRAINT signals_social_alternative_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id)
);
CREATE TABLE public.signals_technical (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signal_id uuid NOT NULL,
  factors jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signals_technical_pkey PRIMARY KEY (id),
  CONSTRAINT signals_technical_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.signals(id)
);