-- Migration 019: Remove Unused Analytics Columns
-- Date: 2025-11-01
-- Purpose: Clean up analytics table by removing 39 period-based and unused columns
--          that are now handled by JSONB columns (score_bucket_performance, backtest_cumulative_returns)

-- All these metrics are now stored in JSONB columns:
-- - score_bucket_performance: contains win_rate, sharpe, avg_return per interval per bucket
-- - backtest_cumulative_returns: contains max_drawdown, cumulative returns, win_rate

BEGIN;

-- Drop period-based metadata columns (not used - new design is run-based, not period-based)
ALTER TABLE analytics DROP COLUMN IF EXISTS period_start;
ALTER TABLE analytics DROP COLUMN IF EXISTS period_end;
ALTER TABLE analytics DROP COLUMN IF EXISTS period_type;

-- Drop win_rate_* columns (7 columns - now in score_bucket_performance JSONB)
ALTER TABLE analytics DROP COLUMN IF EXISTS win_rate_1d;
ALTER TABLE analytics DROP COLUMN IF EXISTS win_rate_3d;
ALTER TABLE analytics DROP COLUMN IF EXISTS win_rate_7d;
ALTER TABLE analytics DROP COLUMN IF EXISTS win_rate_10d;
ALTER TABLE analytics DROP COLUMN IF EXISTS win_rate_14d;
ALTER TABLE analytics DROP COLUMN IF EXISTS win_rate_30d;
ALTER TABLE analytics DROP COLUMN IF EXISTS win_rate_90d;

-- Drop sharpe_ratio_* columns (7 columns - now in score_bucket_performance JSONB)
ALTER TABLE analytics DROP COLUMN IF EXISTS sharpe_ratio_1d;
ALTER TABLE analytics DROP COLUMN IF EXISTS sharpe_ratio_3d;
ALTER TABLE analytics DROP COLUMN IF EXISTS sharpe_ratio_7d;
ALTER TABLE analytics DROP COLUMN IF EXISTS sharpe_ratio_10d;
ALTER TABLE analytics DROP COLUMN IF EXISTS sharpe_ratio_14d;
ALTER TABLE analytics DROP COLUMN IF EXISTS sharpe_ratio_30d;
ALTER TABLE analytics DROP COLUMN IF EXISTS sharpe_ratio_90d;

-- Drop max_drawdown_* columns (7 columns - now in backtest_cumulative_returns JSONB)
ALTER TABLE analytics DROP COLUMN IF EXISTS max_drawdown_1d;
ALTER TABLE analytics DROP COLUMN IF EXISTS max_drawdown_3d;
ALTER TABLE analytics DROP COLUMN IF EXISTS max_drawdown_7d;
ALTER TABLE analytics DROP COLUMN IF EXISTS max_drawdown_10d;
ALTER TABLE analytics DROP COLUMN IF EXISTS max_drawdown_14d;
ALTER TABLE analytics DROP COLUMN IF EXISTS max_drawdown_30d;
ALTER TABLE analytics DROP COLUMN IF EXISTS max_drawdown_90d;

-- Drop avg_return_* columns (7 columns - now in score_bucket_performance JSONB)
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_return_1d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_return_3d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_return_7d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_return_10d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_return_14d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_return_30d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_return_90d;

-- Drop avg_alpha_* columns (7 columns - now calculated as alpha_vs_spy/alpha_vs_qqq)
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_alpha_1d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_alpha_3d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_alpha_7d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_alpha_10d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_alpha_14d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_alpha_30d;
ALTER TABLE analytics DROP COLUMN IF EXISTS avg_alpha_90d;

-- Drop sector_performance JSONB column (not generated by pipeline, not used by frontend)
-- Frontend uses top_sector/worst_sector fields instead
ALTER TABLE analytics DROP COLUMN IF EXISTS sector_performance;

COMMIT;

-- Summary:
-- Removed 39 columns total:
--   3 period metadata columns
--   7 win_rate_* columns
--   7 sharpe_ratio_* columns  
--   7 max_drawdown_* columns
--   7 avg_return_* columns
--   7 avg_alpha_* columns
--   1 sector_performance JSONB column
--
-- Table reduced from 82 columns → 43 columns
-- All removed data is preserved in JSONB columns or replaced by better metrics
