# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Smoke

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run smoke test (no network)
        env:
          OPENAI_API_KEY: ''
        run: |
          python tools/smoke_test.py
      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: smoke-outputs
          path: outputs/**
