name: VP Investments Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: vp-pipeline
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  # Scheduling is disabled during test phase; re-enable cron + gating later

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies (uv)
        run: |
          uv pip install --system -r requirements.txt

      - name: Run pipeline (once)
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Reddit API (required for scraping Reddit)
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python "run_all.py" --once --stream --timeout 1800

      - name: Prepare Pages index
        run: |
          mkdir -p outputs
          echo '<meta http-equiv="refresh" content="0; url=dashboard/dashboard.html">' > outputs/index.html

      - name: Upload outputs artifact
        uses: actions/upload-artifact@v4
        with:
          name: vp-outputs-${{ github.run_number }}
          path: outputs
          if-no-files-found: warn
          retention-days: 30

      - name: Upload logs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vp-logs-${{ github.run_number }}
          path: outputs/logs
          if-no-files-found: warn
          retention-days: 30

      - name: Persist outputs to data branch (cumulative)
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TS=$(date -u +'%Y%m%dT%H%M%SZ')
          rm -rf data-repo
          git clone "https://x-access-token:${TOKEN}@github.com/${REPO}.git" data-repo
          cd data-repo
          if git ls-remote --exit-code --heads origin data > /dev/null 2>&1; then
            git checkout data
          else
            git checkout --orphan data
            git commit --allow-empty -m "Initialize data branch"
            git push origin data
          fi
          mkdir -p "runs/${TS}"
          rsync -a --delete ../outputs/ "runs/${TS}/"
          git add runs
          git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m "Add run ${TS}" || echo "No changes to commit"
          git push origin data

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: outputs

  deploy:
    needs: run
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
